define(["backbone"],function(){
	var router = Backbone.Router.extend({
		routes:{
			// key : val 
			// key 是路由值(访问路径里#号后的值)
			// val 是对应的处理函数名
			"homepage":"homepage",
			"my":"my",
			"myOrder":"myOrder",
			"obligation":"myOrder",
			"accept":"myOrder",
			"evaluate":"myOrder",
			"refund":"myOrder",
			"flashMarket":"flashMarket",
			"freshOrder":"freshOrder",
			"shoppingCar":"shoppingCar",
			"point":"point",
			"vipCenter":"vipCenter",
			"locating":"locating",
			"crazy":"crazy",
			"myTicket":"myTicket",
			"customService":"customService",
			"aboutUs":"aboutUs",
			"address":"address",
			"search":"search"
		},
		// 这里的home 对应上面的val
		homepage:function(){
			require(["modules/homepage/homepage"],function(h){
				h.render();
			})
		},
		my:function(){
			require(["modules/my/my"],function(m){
				m.render();
			})
		},
		myOrder:function(){
			require(["modules/myOrder/list"],function(l){
				l.render();
			})
		},
		flashMarket:function(){
			require(["modules/flashMarket/flashMarket"],function(m){
				m.render()
			})
		},
		freshOrder:function(){
			console.log(1)
			require(["modules/freshOrder/freshOrder"],function(f){
				f.render()
			})
		},
		shoppingCar:function(){
			require(["modules/shoppingCar/shoppingCar"],function(s){
				s.render()
			})
		},
		point:function(){
			require(["modules/point/point"],function(p){
				p.render()
			})
		},
		vipCenter:function(){
			require(["modules/vipCenter/vip"],function(v){
				v.render()
			})
		},
		locating:function(){
			require(["modules/location/locating"],function(l){
				l.render()
			})
		},
		crazy:function(){
			require(["modules/crazy/crazy"],function(c){
				c.render()
			})
		},
		myTicket:function(){
			require(["modules/myTicket/myTicket"],function(m){
				m.render()
			})
		},
		customService:function(){
			require(["modules/customService/customService"],function(c){
				c.render()
			})
		},
		aboutUs:function(){
			require(["modules/aboutUs/aboutUs"],function(a){
				a.render()
			})
		},
		address:function(){
			require(["modules/address/address"],function(a){
				a.render()
			})
		},
		search:function(){
			require(["modules/search/search"],function(s){
				s.render()
			})
		}
	});
	new router();
});